id: AF5259390
base_file: f8BC2.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-17 13:59:30.005561
  last_modified_at: 2022-06-17 13:59:30.005575
