id: AF5259390
base_file: f5F98.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-17 13:59:29.997489
  last_modified_at: 2022-06-17 13:59:29.997563
